### ISSUE TITLE
Calendar Modul API Error 500

### ISSUE THREAD

**Issue by Faedrak** [humhub/humhub-modules-rest#11]
API endpoint https://{base.url}/api/v1/calendar

Response:
```
 {
     "name": "Internal Server Error",
     "message": "Es ist ein interner Serverfehler aufgetreten.",
     "code": 0,
     "status": 500
 }
```

 I have taken Basic Auth as authentication method

**Comment by luke-** [comment]
Can you please post the error message?

**Comment by martinste1n** [comment]
Same issue at our instance. 

We get the following error in the logs:

`yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\calendar\models\CalendarEntry::recur in /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('recur') #1 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/humhub/modules/content/components/ContentActiveRecord.php(193): yii\db\BaseActiveRecord->__get('recur') #2 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/modules/rest/definitions/CalendarDefinitions.php(29): humhub\modules\content\components\ContentActiveRecord->__get('recur') #3 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/modules/rest/controllers/calendar/CalendarController.php(39): humhub\modules\rest\definitions\CalendarDefinitions::getCalendarEntry(Object(humhub\modules\calendar\models\CalendarEntry)) #4 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/modules/rest/components/BaseContentController.php(76): humhub\modules\rest\controllers\calendar\CalendarController->returnContentDefinition(Object(humhub\modules\calendar\models\CalendarEntry)) #5 [internal function]: humhub\modules\rest\components\BaseContentController->actionFind() #6 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #7 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #8 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('find', Array) #9 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('rest/calendar/c...', Array) #10 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /var/www/vhosts/zentrum-digitalisierung.de/netzwerk.zentrum-digitalisierung.de/index.php(25): yii\base\Application->run() #12 {main}`

**Comment by luke-** [comment]
Will be fixed here: https://github.com/humhub/humhub-modules-rest/pull/40
