### ISSUE TITLE
Documentation: Info about generation of bearer token needed

### ISSUE THREAD

**Issue by beyring** [humhub/humhub-modules-rest#14]
Hi all, 

I am struggling to find information on how to generate or find a bearer token to use as auth method in API requests in humhub, especially to use the wiki api. 

I thought to be lucky here: https://docs.humhub.org/docs/admin/authentication/dev-authentication.md

Unfortunately that page does not exist anymore. 

Any help is much appreciated. 

Thanks in advance and best regards from Munich, 
Ben

**Comment by luke-** [comment]
Hi Ben,

you can either use the REST API with basic auth or can use a secret specified  in the module configuration.

Best 

Lucas

**Comment by beyring** [comment]
Hi Lucas, 

thanks for the hint, found the token in the configuration section of the module. 

Best,
Ben
