### ISSUE TITLE
[Feature Request] JSON webhooks Handler

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub-modules-rest#15]

**Comment by luke-** [comment]
Can you please describe it a little more in detail?

**Comment by ArchBlood** [comment]
Platforms like Discord and many others allow webhooks to be used to post to chat channels via webhooks, this would be very nice to be able to do as well with the Rest API module, this also opens up many other automation possibilities.

**Comment by luke-** [comment]
I like the idea of Webhook Support, but I would rather create a own module for it.

**Comment by ArchBlood** [comment]
Then would it be better to use [REST Hooks](https://resthooks.org/) versus webhook in this issue?

**Comment by ArchBlood** [comment]
And in the case of it being this then this issue should be transferred to the core project with a module label?

**Comment by luke-** [comment]
@ArchBlood  es, for the Webhooks a issue with ModuleIdea label in the Core Repo would be good!

**Comment by ArchBlood** [comment]
Done
