### ISSUE TITLE
AuthController: Return current user details

### ISSUE THREAD

**Issue by yecarri** [humhub/humhub-modules-rest#18]
Currently, the api allows retrieving user data by user id (api/v1/user/{id}) or a complete user list (api/v1/user). Is it planned to implement a user search by login?

**Comment by luke-** [comment]
I think we should add to the User List query the possibility to add filters/searches. Such as the username/Login.

**Comment by subversve** [comment]
Is there an endpoint to get the details of the current user?

**Comment by yurabakhtin** [comment]
@luke- Do you really wanted to add the endpoint for current user details in `AuthController`?
I think better place is `UserController` and I did this as `GET:api/v1/user/current`, please check the PR https://github.com/humhub/humhub-modules-rest/pull/38.

**Comment by luke-** [comment]
@yurabakhtin Is the UserCotnroller not only accessible for administrators?

**Comment by yurabakhtin** [comment]
@luke- `UserController` has no restrictions by permissions, as I described here https://github.com/humhub/tasks/issues/19: any user who can access to API as enabled user in the api module configuration.

**Comment by yecarri** [comment]
Sorry, that was not my request. For some reason I asked for an endopoint to search for a user given his login, for example: api user with login yecarri request all the users with login containing maria.

**Comment by yurabakhtin** [comment]
@yecarri It seems your request was implemented 22 days ago here https://github.com/humhub/humhub-modules-rest/commit/f3dd363c9ab7cdc5a1d6e97d6ad7b4b58ae7bad3#diff-666c020a6d1e6a59ba261ba9316aaa19e27dbd851bcc4fdcaecaa278ddc96c10R35-R36.
If you will update the rest module files to this version you can use this as `/api/v1/user/get-by-username?username=maria`
