### ISSUE TITLE
Add/Remove Comment on a post

### ISSUE THREAD

**Issue by LaRepDuClic** [humhub/humhub-modules-rest#26]
How about adding or removing comment on a content :

Example

- POST https://www.humhub.com/api/v1/comment/byPost/{id} with data { 'user_id': <userId>, 'comment': <comment> }
- DEL https://www.humhub.com/api/v1/comment/byPost/{id} with data { 'user_id': <userId> }

**Comment by ArchBlood** [comment]
Not sure what you mean, you can already GET via `/api/v1/comment/{id}` and DELETE via `/api/v1/comment/{id}` so it would only be natural to be able to POST via `/api/v1/comment/{id}` :thinking:

**Comment by LaRepDuClic** [comment]
Yes we can Get a comment by it's Id, but how can we get alls comments on a post ? And, yes again, we cannot currently Add a new Post on a comment (or am I wrong ?)

**Comment by ArchBlood** [comment]
> Yes we can Get a comment by it's Id, but how can we get alls comments on a post ? And, yes again, we cannot currently Add a new Post on a comment (or am I wrong ?)

Well when you say post a comment this is kind of contradictory as a post and comment are somewhat different in this case level wise that is, but you're right you can't `POST` or `PUT/PATCH` a comment so something like `POST /api/v1/comment/container/{id}` & `PUT /api/v1/comment/{id}` seems to be something more feasible :thinking: 

But looking at the [Events.php](https://github.com/humhub/humhub-modules-rest/blob/master/Events.php#L84) you get the general idea of our to implement it just have to update that file and the [CommentDefinitions.php](https://github.com/humhub/humhub-modules-rest/blob/master/definitions/CommentDefinitions.php) file

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-rest/issues/41
