### ISSUE TITLE
Get Posts only visible for a User

### ISSUE THREAD

**Issue by LaRepDuClic** [humhub/humhub-modules-rest#27]
We can get all posts (GET https://www.humhub.com/api/v1/post) or posts for a container (GET https://www.humhub.com/api/v1/post/container/{id}) but what about :

- Getting posts visible by a single user (according to spaces / private / public state) :
ie. GET https://www.humhub.com/api/v1/post/user/{id}
- Getting posts visible if not connected ?

**Comment by luke-** [comment]
Implemented here: https://github.com/humhub/humhub-modules-rest/pull/40
