### ISSUE TITLE
Get the space ID a task or task container is associated with.

### ISSUE THREAD

**Issue by avillaindesire** [humhub/humhub-modules-rest#34]
Space URL is passed as a property of a task (task -> content -> metadata -> URL), but it doesn't look like the space ID is anywhere in the task. Is there a way to find tasks associated with a space besides parsing that URL and iterating through all the tasks? Ideally, I'd be able to supply a space ID and either get the container ID or tasks associated with it.

**Comment by avillaindesire** [comment]
Looking into it a little further, I don't actually see a way to figure out the container ID for a space that has no tasks. there isn't an api/vi/tasks/container endpoint that lists all of the containers. Since Container ID is a required parameter for many of the endpoints, it seems like that would be more interesting to have. Maybe add the space ID into that call?

**Comment by luke-** [comment]
The Rest API is unfortunately still not complete or optimal in some places.

At this time you can fetch all content containers via following call:
https://www.humhub.com/en/marketplace/rest/docs/html/content.html#tag/Container/paths/~1content~1container/get
You may need to filter the object_class to 'Spaces' only. 

However, it would be nicer if space/user metadata also contain their ContentContainer ID.
I've created an issue here: https://github.com/humhub/humhub-modules-rest/issues/35

I've you like you're welcome to create a PR for this!
