### ISSUE TITLE
Create Endpoint for Mail module

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-rest#36]
Create/Send Mail Message to users (as Administrator also  `As other user`. 

Optional other endpoints for:
- List conversation
- Manage participants
- Create/Delete/Edit entries of a conversation
- Manage tags

**Comment by buddh4** [comment]
Shouldn't we think about a solution in which modules can inject API enpoints to this module instead of adding all modules to this module?

**Comment by luke-** [comment]
@buddh4 This is definitely planned but not now.

**Comment by yurabakhtin** [comment]
@luke- Released endpoints:

**Conversations:**

- `api/v1/mail`:GET - Conversations list
- `api/v1/mail/{$messageId}`:GET - Conversation details
- `api/v1/mail`:POST - Create new conversation

**Participants:**
- `api/v1/mail/{$messageId}/users`:GET - Users list of conversation
- `api/v1/mail/{$messageId}/user/{$userId}:POST - Add user to conversation
- `api/v1/mail/{$messageId}/user/{$userId}:DELETE - Leave user from conversation

**Entries:**
- `api/v1/mail/{$messageId}/entries`:GET - Entries list of conversation
- `api/v1/mail/{$messageId}/entry`:POST - Add an entry into conversation
- `api/v1/mail/{$messageId}/entry/{$entryId}`:GET - Entry details
- `api/v1/mail/{$messageId}/entry/{$entryId}`:PUT - Update entry
- `api/v1/mail/{$messageId}/entry/{$entryId}`:DELETE - Delete entry from conversation

Manage tags is not done yet.

**Comment by yurabakhtin** [comment]
@luke- https://github.com/humhub/humhub-modules-rest/commit/a7561637197cf86f9a253aa20f442d83ac42cc2b

**Tags:**

- `api/v1/mail/<messageId:\d+>/tags`:GET - Tags list of the conversation
- `api/v1/mail/<messageId:\d+>/tags`:PUT - Update tags of the conversation
  - sample request:
```
{
    "tags": ["First", "Second", "Tag from API"]
}
```

I think we should create doc page to display all these new endpoints.
Note: doc pages like this https://www.humhub.com/en/marketplace/rest/docs/html/user.html have JS bug in Chrome browser: when I scroll in down it is always scrolled up so I cannot read it. It works better in Safari and FireFox browsers.

**Comment by yurabakhtin** [comment]
@luke- New changes - https://github.com/humhub/humhub-modules-rest/pull/37#issuecomment-721186063
