### ISSUE TITLE
adding member to group

### ISSUE THREAD

**Issue by rflores-iterate** [humhub/humhub-modules-rest#39]
action:
https://github.com/humhub/humhub-modules-rest/blob/master/controllers/user/GroupController.php#L113
this action **_does add the member to the group_**

however **_always_** returns:
https://github.com/humhub/humhub-modules-rest/blob/master/controllers/user/GroupController.php#L134

**_never_** returns: (which it should )
https://github.com/humhub/humhub-modules-rest/blob/master/controllers/user/GroupController.php#L131

url being used:
`api/v1/user/group/4/member?userId=2317&isManager=0`

any idea on why?  

v0.1.3 - Rest
HHv = 1.4.0

**Comment by luke-** [comment]
I think this related to this change.

https://github.com/humhub/humhub/commit/4053d989c325c2a5ba70d317c812a2e51a1845d8#diff-a48b33b5fa0409f1ae133b00086682c396c4f4ea470d30d47823c15231284e9d

The latest master of the REST API module requires HumHub 1.7
https://github.com/humhub/humhub-modules-rest/blob/master/module.json#L10
