### ISSUE TITLE
Do the Activity endpoints work as expected?

### ISSUE THREAD

**Issue by avillaindesire** [humhub/humhub-modules-rest#42]
When I go to an activity endpoint for a container (e.g. {{API_URL}}/activity/container/5), it always reports 0 activity. What elements go into the activity endpoints? Posts, comments, etc? If they are working on you end, then I'm probably doing something wrong on my end...

On a separate note, is there a place to store information on the quirks of using the REST API? As an example, when I was trying to update the status of a task through the API, I learned that you cannot go from status 1 directly to 5. Trying to do so will change the status to 2. Running the same call again will then change it from 2 to 5. Having a place to store that kind of knowledge would benefit others in the future.

Thanks for all your work!

**Comment by luke-** [comment]
Should be fixed in 0.2.0-beta.1
