### ISSUE TITLE
Not compatible with Humhub 1.8

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub-modules-rest#51]
`space_id` field is removed in Humhub 1.8:
https://github.com/humhub/humhub-modules-rest/blob/e0c83d9cff2f4232acf15645ef3f6238967ebe4d/definitions/UserDefinitions.php#L75

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub-modules-rest/pull/52
