### ISSUE TITLE
Task Usage Page 404

### ISSUE THREAD

**Issue by rvca1140** [humhub/humhub-modules-rest#7]
I'm trying to use the Rest API to generate tasks on a specific Space is this possible? 

The current link to the Tasks API is producing a 404 error - https://htmlpreview.github.io/?https://github.com/humhub/humhub-modules-rest/blob/master/docs/html/tasks.html

**Comment by luke-** [comment]
Try this: https://github.com/humhub/humhub-modules-rest/blob/master/docs/html/task.html
